optimized

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,14 +3,11 @@ name: CI/CD Pipeline
 on:
   push:
     branches: [master]
-  pull_request:
-    branches: [master]
 
 jobs:
-  build-backend:
-    name: Build & Test Backend
+  package-backend:
+    name: Build & push Backend image
     runs-on: ubuntu-latest
-    if: false
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -23,11 +20,6 @@ jobs:
 
       - name: Install Maven
         run: sudo apt-get install -y maven
-
-      - name: Build & Test Backend
-        run: |
-          cd backend/restful-web-services
-          mvn clean install -U
 
       - name: Run Tests & Generate Coverage
         run: |
@@ -45,114 +37,7 @@ jobs:
         with:
           name: backend-classes
           path: backend/restful-web-services/target/classes
-
-  build-frontend:
-    name: Build & Test Frontend
-    runs-on: ubuntu-latest
-    if: false
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '18'
-
-      - name: Install Dependencies
-        run: |
-          cd frontend/todo
-          npm install
-
-      - name: Run Frontend Tests & Generate Coverage
-        run: |
-          cd frontend/todo
-          npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox --code-coverage
-
-      - name: Upload Frontend Coverage Report
-        uses: actions/upload-artifact@v4
-        with:
-          name: frontend-coverage
-          path: frontend/todo/coverage
-
-  sonar-analysis:
-    name: SonarQube Analysis
-    runs-on: ubuntu-latest
-    needs: [build-backend, build-frontend]
-    if: false
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Cache SonarQube Dependencies
-        uses: actions/cache@v3
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-
-      - name: Restore Compiled Java Classes
-        uses: actions/download-artifact@v4
-        with:
-          name: backend-classes
-          path: backend/restful-web-services/target/classes
       
-      - name: Restore Frontend Coverage Report
-        uses: actions/download-artifact@v4
-        with:
-          name: frontend-coverage
-          path: frontend/todo/coverage
-
-      - name: Restore backend Coverage Report
-        uses: actions/download-artifact@v4
-        with:
-          name: backend-coverage
-          path: backend/restful-web-services/target/site/jacoco
-
-      - name: Run SonarQube Analysis
-        run: |
-          npx sonar-scanner -Dsonar.token=${{ secrets.SONAR_TOKEN }}
-
-      - name: Check SonarQube Quality Gate
-        run: |
-          sleep 10
-          RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=fullapp_todoapp")
-          
-          echo "SonarQube Quality Gate Response:"
-          echo "$RESPONSE" | jq .
-
-          STATUS=$(echo "$RESPONSE" | jq -r .projectStatus.status)
-
-          if [[ "$STATUS" != "OK" ]]; then
-            echo "❌ Quality Gate Failed!"
-            exit 1
-          else
-            echo "✅ Quality Gate Passed!"
-          fi
-        shell: bash
-  
-  package-backend:
-    name: Package Backend
-    runs-on: ubuntu-latest
-    outputs:
-      BACKEND_VERSION: ${{ steps.set-backend-version.outputs.BACKEND_VERSION }}
-    #needs: sonar-analysis
-    #if: false
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-      
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-
-      - name: Install Maven
-        run: sudo apt-get install -y maven
-
       - name: Backend Version
         id: set-backend-version
         run: |
@@ -182,12 +67,8 @@ jobs:
           docker push ${{ secrets.DOCKERHUB_REPO }}/backend-app:${{ github.sha }}
 
   package-frontend:
-    name: Package Frontend
+    name: Build & push Frontend image
     runs-on: ubuntu-latest
-    outputs:
-      APP_VERSION: ${{ steps.app-version.outputs.APP_VERSION }}
-    #needs: sonar-analysis
-    #if: false
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -197,6 +78,22 @@ jobs:
         with:
           node-version: '18'
 
+      - name: Install Dependencies
+        run: |
+          cd frontend/todo
+          npm install
+
+      - name: Run Frontend Tests & Generate Coverage
+        run: |
+          cd frontend/todo
+          npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox --code-coverage
+
+      - name: Upload Frontend Coverage Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: frontend-coverage
+          path: frontend/todo/coverage
+
       - name: Frontend Version
         id: app-version
         run: |
@@ -204,12 +101,10 @@ jobs:
           echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
           echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_OUTPUT"
 
-
       - name: Build Frontend Docker Image
         run: |
           echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
           cd frontend/todo
-          npm install
           npm run build --prod
           docker build \
             -t ${{ secrets.DOCKERHUB_REPO }}/frontend-app:${{ env.APP_VERSION }} \
@@ -221,10 +116,62 @@ jobs:
           docker push ${{ secrets.DOCKERHUB_REPO }}/frontend-app:${{ env.APP_VERSION }}
           docker push ${{ secrets.DOCKERHUB_REPO }}/frontend-app:${{ github.sha }}
 
+  sonar-analysis:
+    name: SonarQube Analysis
+    runs-on: ubuntu-latest
+    needs: [package-backend, package-frontend]
+    steps:
+      - name: Cache SonarQube Dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+
+      - name: Restore Compiled Java Classes
+        uses: actions/download-artifact@v4
+        with:
+          name: backend-classes
+          path: backend/restful-web-services/target/classes
+
+      - name: Restore backend Coverage Report
+        uses: actions/download-artifact@v4
+        with:
+          name: backend-coverage
+          path: backend/restful-web-services/target/site/jacoco
+      
+      - name: Restore Frontend Coverage Report
+        uses: actions/download-artifact@v4
+        with:
+          name: frontend-coverage
+          path: frontend/todo/coverage
+
+      - name: Run SonarQube Analysis
+        run: |
+          npx sonar-scanner -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+
+      - name: Check SonarQube Quality Gate
+        run: |
+          sleep 10
+          RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=fullapp_todoapp")
+          
+          echo "SonarQube Quality Gate Response:"
+          echo "$RESPONSE" | jq .
+
+          STATUS=$(echo "$RESPONSE" | jq -r .projectStatus.status)
+
+          if [[ "$STATUS" != "OK" ]]; then
+            echo "❌ Quality Gate Failed!"
+            exit 1
+          else
+            echo "✅ Quality Gate Passed!"
+          fi
+        shell: bash
+
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
-    needs: [package-backend, package-frontend]
+    needs: [build-backend, build-frontend]
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -233,6 +180,12 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y ansible
+
+      - name: Install Ansible AWS collection
+        run: ansible-galaxy collection install amazon.aws
+
+      - name: Install AWS dependencies
+        run: pip install boto3 botocore
 
       - name: Setup SSH Key
         run: |
